name: py2
dependencies:
  - python==2.7.13
  - scipy==0.19.0
  - numpy==1.13.1
  - pandas==0.20.3
  - matplotlib
  - jupyter==1.0.0
  - h5py==2.7.0
  - scikit-learn==0.18.1
  - pip:
    - captcha==0.2.4
    - opencv_python==3.3.0.10
    - seaborn==0.8.1
    - pillow==4.3.0
    - tensorflow_gpu==1.3.0
    - keras==2.0.8
    - pydot_ng==1.0.0
    - nvidia-ml-py==7.352.0
    - tqdm
